# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 401)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Baud_label = QtWidgets.QLabel(self.centralwidget)
        self.Baud_label.setGeometry(QtCore.QRect(20, 17, 51, 21))
        self.Baud_label.setObjectName("Baud_label")
        self.Port_label = QtWidgets.QLabel(self.centralwidget)
        self.Port_label.setGeometry(QtCore.QRect(20, 50, 61, 17))
        self.Port_label.setObjectName("Port_label")
        self.Baud_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Baud_lineEdit.setGeometry(QtCore.QRect(80, 10, 113, 27))
        self.Baud_lineEdit.setObjectName("Baud_lineEdit")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Port_lineEdit.setGeometry(QtCore.QRect(80, 50, 113, 27))
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.Open_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Button.setGeometry(QtCore.QRect(230, 10, 97, 27))
        self.Open_Button.setObjectName("Open_Button")
        self.Close_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Close_Button.setGeometry(QtCore.QRect(230, 50, 97, 27))
        self.Close_Button.setObjectName("Clsoe_Butto")
        self.Status_label = QtWidgets.QLabel(self.centralwidget)
        self.Status_label.setGeometry(QtCore.QRect(340, 30, 66, 21))
        self.Status_label.setObjectName("Status_label")
        self.Show_label = QtWidgets.QLabel(self.centralwidget)
        self.Show_label.setGeometry(QtCore.QRect(420, 30, 131, 21))
        self.Show_label.setObjectName("Show_label")
        self.Speed_label = QtWidgets.QLabel(self.centralwidget)
        self.Speed_label.setGeometry(QtCore.QRect(20, 100, 66, 21))
        self.Speed_label.setObjectName("Speed_label")
        self.Angle_label = QtWidgets.QLabel(self.centralwidget)
        self.Angle_label.setGeometry(QtCore.QRect(20, 140, 66, 21))
        self.Angle_label.setObjectName("Angle_label")
        self.Hight_label = QtWidgets.QLabel(self.centralwidget)
        self.Hight_label.setGeometry(QtCore.QRect(20, 180, 66, 21))
        self.Hight_label.setObjectName("Hight_label")
        self.Speed_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Speed_lineEdit.setGeometry(QtCore.QRect(90, 100, 101, 27))
        self.Speed_lineEdit.setObjectName("Speed_lineEdit")
        self.Angle_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Angle_lineEdit.setGeometry(QtCore.QRect(90, 140, 101, 27))
        self.Angle_lineEdit.setObjectName("Angle_lineEdit")
        self.Hight_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Hight_lineEdit.setGeometry(QtCore.QRect(90, 180, 101, 27))
        self.Hight_lineEdit.setObjectName("Hight_lineEdit")
        self.Cur_speed_label = QtWidgets.QLabel(self.centralwidget)
        self.Cur_speed_label.setGeometry(QtCore.QRect(240, 100, 71, 21))
        self.Cur_speed_label.setObjectName("Cur_speed_label")
        self.Cur_angle_label = QtWidgets.QLabel(self.centralwidget)
        self.Cur_angle_label.setGeometry(QtCore.QRect(240, 140, 71, 21))
        self.Cur_angle_label.setObjectName("Cur_angle_label")
        self.Cur_hight_label = QtWidgets.QLabel(self.centralwidget)
        self.Cur_hight_label.setGeometry(QtCore.QRect(240, 180, 71, 21))
        self.Cur_hight_label.setObjectName("Cur_hight_label")
        self.Show_speed_label = QtWidgets.QLabel(self.centralwidget)
        self.Show_speed_label.setGeometry(QtCore.QRect(320, 100, 111, 21))
        self.Show_speed_label.setObjectName("Show_speed_label")
        self.Show_angle_label = QtWidgets.QLabel(self.centralwidget)
        self.Show_angle_label.setGeometry(QtCore.QRect(320, 140, 121, 21))
        self.Show_angle_label.setObjectName("Show_angle_label")
        self.Show_hight_label = QtWidgets.QLabel(self.centralwidget)
        self.Show_hight_label.setGeometry(QtCore.QRect(320, 180, 121, 21))
        self.Show_hight_label.setObjectName("Show_hight_label")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(20, 230, 81, 27))
        self.Start_Button.setObjectName("Start_Button")
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setGeometry(QtCore.QRect(20, 280, 81, 27))
        self.Stop_Button.setObjectName("Stop_Button")
        self.Front_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Front_Button.setGeometry(QtCore.QRect(140, 230, 81, 27))
        self.Front_Button.setObjectName("Front_Button")
        self.Back_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_Button.setGeometry(QtCore.QRect(240, 230, 81, 27))
        self.Back_Button.setObjectName("Back_Button")
        self.Left_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Left_Button.setGeometry(QtCore.QRect(140, 280, 81, 27))
        self.Left_Button.setObjectName("Left_Button")
        self.Right_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Right_Button.setGeometry(QtCore.QRect(240, 280, 81, 27))
        self.Right_Button.setObjectName("Right_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Baud_label.setText(_translate("MainWindow", "波特率："))
        self.Port_label.setText(_translate("MainWindow", "端口号："))
        self.Baud_lineEdit.setText(_translate("MainWindow", "115200"))
        self.Port_lineEdit.setText(_translate("MainWindow", "COM1"))
        self.Open_Button.setText(_translate("MainWindow", "打开串口"))
        self.Close_Button.setText(_translate("MainWindow", "关闭串口"))
        self.Status_label.setText(_translate("MainWindow", "目前状态："))
        self.Show_label.setText(_translate("MainWindow", "串口未打开"))
        self.Speed_label.setText(_translate("MainWindow", "发送速度："))
        self.Angle_label.setText(_translate("MainWindow", "发送角度："))
        self.Hight_label.setText(_translate("MainWindow", "发送高度："))
        self.Cur_speed_label.setText(_translate("MainWindow", "当前速度："))
        self.Cur_angle_label.setText(_translate("MainWindow", "当前角度："))
        self.Cur_hight_label.setText(_translate("MainWindow", "当前高度："))
        self.Show_speed_label.setText(_translate("MainWindow", "0.00       m/s"))
        self.Show_angle_label.setText(_translate("MainWindow", "0.00       度"))
        self.Show_hight_label.setText(_translate("MainWindow", "0.00       m"))
        self.Start_Button.setText(_translate("MainWindow", "运行"))
        self.Stop_Button.setText(_translate("MainWindow", "停止"))
        self.Front_Button.setText(_translate("MainWindow", "前进"))
        self.Back_Button.setText(_translate("MainWindow", "后退"))
        self.Left_Button.setText(_translate("MainWindow", "左转"))
        self.Right_Button.setText(_translate("MainWindow", "右转"))

